### ISSUE TITLE
fix/webrtcroom_limitconnection

### ISSUE THREAD

**Issue by tkdalsss** [Meteor-hanaro/Frontend#115]
## 📌 Feature Issue

화상상담방 인원 제한 기능 추가후 연결 문제 해결

## 📝 To-do

- [ ] 모르겠음.. 코드를 더 봐야할듯
- [x] participants -> channel 별 participants로 분리
- [ ] 카메라 상호 연결 안되는 이슈 수정하기

**Comment by yhkkkkxx** [comment]
웹소켓 서버 잘 작동하는지 먼저 확인 부탁해욘

**Comment by tkdalsss** [comment]
→ 화상상담방 입장 제한은 되는데 participants 변수 선언한게 8888 websocket 전체 인원 제한하는 변수로 되어서 → 채널별 participants로 바꾸는중 → map이나 뭐 적절한거 아무거나
