### ISSUE TITLE
feature/rebalancing-page-detail

### ISSUE THREAD

**Issue by yhkkkkxx** [Meteor-hanaro/Frontend#15]
## 📌 Feature Issue

화상채팅 각 단계별 페이지 구현 및 UI

## 📝 To-do

- [x] WebRTC, WebSocket 리액트 context로 관리
- [x] 리밸런싱 화면
- [x] 본인인증 신분증 캡쳐 화면
- [x] 계약서 작성 화면
