### ISSUE TITLE
feature/consentView

### ISSUE THREAD

**Issue by jiyeoon00** [Meteor-hanaro/Frontend#31]
## 📌 Feature Issue

펀드 가입 시 설명서, 약관 등 확인 후 동의하는 화면을 구현합니다.

## 📝 To-do

- [x] 동의할 서류 체크 리스트 구현
- [x] 서류 클릭 시 상세 내용 띄워주기
- [x] 체크 클릭 시 체크 리스트에 반영
- [ ] css
