### ISSUE TITLE
feature/vip-main-view

### ISSUE THREAD

**Issue by kgw0124** [Meteor-hanaro/Frontend#45]
## 📌 Feature Issue

/vip/main 구현

## 📝 To-do

- [x] Header - 로그인한 Vip 이름 출력
- [x] Main - /api/vip/main response 화면에 뿌리기
- [x] style.css 충돌 수정
